# Diameter classes
dc: {1: 7.5, 2: 15, 3: 25, 4: 35, 5: 45, 6: 55, 7: 65, 8: 75, 9: 85, 10: 95, 11: 150, 12: 9999}

simulation_region:
# This values cover France only
# Check conversion on https://epsg.io/transform
# Apply conversion using the `Proj` package:
# using Proj
# trans = Proj.Transformation("EPSG:4326", "EPSG:3035", always_xy=true)
# (X,Y) = trans(2.35,48.85) # Paris
  cres_epsg_id: 3035
  x_lb: 2.980269469245921e6 # -6 in EPSG:4326 (i.e. WGS 84 ellipsoid unprojected)
  x_ub: 4.252324473944207e6 # 9
  y_lb: 2.131472196486537e6 # 41
  y_ub: 3.210471068338138e6 # 52
  xres: 8000 # meters
  yres: 8000 # meters
resource_init_regions: ["fr"] 
years:
  start: 2021
  step:  1
  end:   2024 
ft_list:  ${SCENARIO_PATH}/forest_types.txt

